### ISSUE TITLE
When installing headless, Pi zero must have static IP

### ISSUE THREAD

**Issue by mytechguyri** [OpenRepeater/scripts#21] opened 2019-01-19 18:47 UTC
Due to the wifi dropping briefly during install, when installing on a Pi zero, if a static IP is not specifically configured in /etc/dhcpcd.conf 
the Pi may receive a different IP when  the network comes back up, resulting in the SSH session terminating, and an aborted install.    A static IP ensures the SSH session will continue once the network reconnects.

**Comment by mytechguyri** [comment] 2019-01-19 18:51
Sample block for static IP in /etc/dhcpcd.conf

interface wlan0
static ip_address=192.168.1.74/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1

Adjust addresses as appropriate for your specific network.

**Comment by bobruddy** [comment] 2019-01-30 05:59
The culprit is the network-manager package installed in install_orp_dependancies function. By default this utility randomizes your mac addresses every time you bring up an interface. Theory is that if you are at a place that tracks behavior based on mac addresses it will protect your privacy. 

Option1: remove that package from the dependencies. I can't find anything using its features. I took this out and did a fresh build. Whole build on a PI3 took 26 minutes over wifi and was rock solid. Connection never hiccuped. 

Option2: before the dependency function. Setup /etc/NetworkManager/conf.d with a config file to disable the randomization. This will stop mac address changing. Yet when interfaces are first configured (typically boot-up) the wifi network connection is unstable for a few minutes. The utility is trying to determine which network path is best so its testing things. There might be a way to tune it. Not sure. Running a full install test to see how well this works as part of the automated build. I know this works as an after configuration. 

Posted in slack #general for feedback.

**Comment by alleghenycreative** [comment] 2019-02-09 22:01
Closing because of removal of network-manager package. Feedback seems to indicate the problem is solved.

**Closed as completed by alleghenycreative** 2019-02-09 22:01 UTC
